version: '3.8'

services:
  db:
    image: postgres:14
    container_name: shortener_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrepass
      POSTGRES_DB: shortener_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: shortener_redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: shortener_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data: